export enum TEXTS {
  NEW_CARS = "NEW CARS",
  USED_CARS = "USED CARS",
  MY_PROFILE = "MY PROFILE",
  FEATURED_CARS = "Featured Cars",
  FIND_YOUR_DREAM_CAR = "FIND YOUR DREAM CAR",
  BOOKING_DETAILS = "Booking Details",
}
